sonar.projectKey=TR-Pruma_Pruma
sonar.organization=tr-pruma
sonar.projectName=Pruma

sonar.sources=pruma/src/main/java
sonar.tests=pruma/src/test/java
sonar.java.binaries=pruma/target/classes

sonar.sourceEncoding=UTF-8
sonar.language=java
